import eslint from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import eslintConfigPrettier from "eslint-config-prettier/flat";
import eslintPluginAstro from "eslint-plugin-astro";
import globals from "globals";
import tseslint from "typescript-eslint";

const eslintConfig = defineConfig([
  eslint.configs.recommended,
  tseslint.configs.recommended,
  eslintConfigPrettier,
  ...eslintPluginAstro.configs["jsx-a11y-strict"],
  {
    languageOptions: {
      globals: globals.node
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off"
    }
  },
  globalIgnores([
    "build/",
    "dist/",
    "out/",
    "out-tsc/",
    "tmp/",
    ".output/",
    "coverage/",
    "coverage/**",
    "*.tgz",
    "node_modules/",
    "jspm_packages/",
    ".pnp",
    ".pnp.*",
    ".yarn/*",
    ".npm",
    ".yarn-integrity",
    ".pnpm-store",
    ".lock-wscript",
    ".astro/",
    ".next/",
    ".nuxt/",
    ".vercel/",
    ".svelte-kit/",
    ".vitepress/cache/",
    ".vitepress/dist/",
    ".turbo/",
    ".netlify/",
    ".wrangler",
    "pids",
    "*.pid",
    "*.seed",
    "*.pid.lock",
    ".lcov",
    ".nyc_output/",
    ".vitest/",
    ".playwright/",
    "playwright-report/",
    "test-results/",
    ".lib-cov",
    ".grunt",
    "typings/",
    "logs/",
    "*.log",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "pnpm-debug.log*",
    "lerna-debug.log*",
    ".env*",
    ".dev.vars",
    "*.tsbuildinfo",
    "next-env.d.ts",
    ".deno/",
    ".bun",
    ".DS_Store",
    "._*",
    ".Spotlight-V100",
    ".Trashes",
    "ehthumbs.db",
    "Thumbs.db",
    "*.pem",
    "*.key",
    "*.cert",
    ".idea/",
    ".project",
    ".classpath",
    ".c9/",
    "*.launch",
    "*.sublime-workspace",
    "*.sublime-project",
    ".vscode/*",
    "!.vscode/settings.json",
    "!.vscode/tasks.json",
    "!.vscode/launch.json",
    "!.vscode/extensions.json",
    "*.swp",
    "*.swo",
    "*~",
    "storybook-static/",
    ".sentryclirc",
    "*.lock",
    "*.lockb",
    "npm-shrinkwrap.json",
    "pnpm-lock.yaml",
    "*LICENSE*",
    "*LICENSES*",
    "license",
    "licenses"
  ])
]);

export default eslintConfig;
